using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        //The DatabaseGenerated attribute with the None parameter on the CourseID property 
        //specifies that primary key values are provided by the user rather than generated by the database.
        //business need in most instance. Ex ECON100
        [Display(Name = "Number")]
        public int CourseID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }

        [Range(0, 5)]
        public int Credits { get; set; }

        public int DepartmentID { get; set; }

        public virtual Department Department { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }
        //The Enrollments property is a navigation property. 
        //A Course entity can be related to any number of Enrollment entities.
        //this DatabaseGeneratedAttribute lets you enter the primary key for the course 
        //rather than having the database generate it.

        public virtual ICollection<Instructor> Instructors { get; set; }
    }
}